-- Insert skills for Admin Support, Data Entry & Transcription Services
INSERT INTO skills (skill, created_at, updated_at) VALUES
('Microsoft Office', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Google Docs', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Express Scribe', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('CRM', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('WordPress', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Descript', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Otter.ai', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Data Processing', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Audio Transcription', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Video Transcription', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Data Scraping', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Data Extraction', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- Insert skills for Admin Support, Virtual Assistance
INSERT INTO skills (skill, created_at, updated_at) VALUES
('Email Management', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Microsoft Office Suite', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Google Workspace', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Canva', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Slack', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Asana', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Administrative Support', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Email Marketing', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- Insert skills for Customer Service, Customer Service & Tech Support
INSERT INTO skills (skill, created_at, updated_at) VALUES
('Online Chat Support', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Troubleshooting', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Networking', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('System Administration', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Network Administration', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('HelpDesk', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('TeamViewer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Terminal/Command Prompt', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Ping/Traceroute for Network Diagnostics', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- Insert skills for Data Science & Analytics, AI & Machine Learning
INSERT INTO skills (skill, created_at, updated_at) VALUES
('Deep Learning', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('PyTorch', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('TensorFlow', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Natural Language Processing', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Machine Learning', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Python', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Data Science', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Data Analysis', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Generative AI', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Supervised Learning', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Unsupervised Learning', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Model Evaluation & Tuning', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);


-- Insert skills for Design & Creative, Art & Illustration
INSERT INTO skills (skill, created_at, updated_at) VALUES
('Adobe Photoshop', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Graphic Design', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Illustration', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Adobe Illustrator', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Affinity Designer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Inkscape', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);


-- Insert skills for Design & Creative, Audio & Music Production
INSERT INTO skills (skill, created_at, updated_at) VALUES
('Logic Pro X', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Music Composition', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Sound Mixing', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Audio Mastering', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Audio Editing', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Music Production', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Audio Restoration', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Noise Reduction', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Avid Pro Tools', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('FL Studio', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- Insert skills for Design & Creative, Branding & Logo Design
INSERT INTO skills (skill, created_at, updated_at) VALUES
('Adobe Photoshop', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Figma / Adobe XD', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Canva', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Brand Identity & Guidelines', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Adobe InDesign', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Branding', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Brand Guidelines', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- Insert skills for Design & Creative, Graphic, Editorial & Presentation Design
INSERT INTO skills (skill, created_at, updated_at) VALUES
('Microsoft PowerPoint', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Infographics', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Keynote', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Adobe Photoshop', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Adobe InDesign', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Figma', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Proofreading', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Editorial Design', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Layout Design', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Google Slides', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- Insert skills for Design & Creative, Video & Animation
INSERT INTO skills (skill, created_at, updated_at) VALUES
('Adobe Premiere Pro', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Final Cut Pro', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('DaVinci Resolve', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('CapCut', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Filmora', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('iMovie', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Blender', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Adobe Animate', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Adobe After Effects', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('2D Animation', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('3D Animation', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Motion Graphics', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

--Insert skills for IT & Networking, Database Management & Administration
INSERT INTO skills (skill, created_at, updated_at) VALUES
('MySQL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('PostgreSQL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Microsoft SQL Server', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Oracle Database', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('MongoDB', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Redis', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Cassandra', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Amazon RDS', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Amazon Aurora', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Google Cloud SQL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Google Firestore', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Azure SQL Database', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Administrative Support', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- Insert skills for IT & Networking, ERP/CRM Software
INSERT INTO skills (skill, created_at, updated_at) VALUES
('ERP Implementation', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('CRM Configuration', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Business Process Analysis', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Data Migration', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Workflow Automation', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('User Training', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('System Integration', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Customization (Modules, Fields, Reports)', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Database Management', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('API Usage', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Security Roles & Permissions', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Troubleshooting', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Documentation', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vendor Liaison', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Software Support', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('SAP', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Salesforce', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Oracle NetSuite', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Zoho', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- Insert skills for Sales & Marketing, Digital Marketing
INSERT INTO skills (skill, created_at, updated_at) VALUES
('SEO', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('SEM', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Social Media Marketing', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Content Marketing', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Email Marketing', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Google Ads', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Meta Ads', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Google Analytics', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('GA4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Conversion Rate Optimization (CRO)', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('A/B Testing', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Marketing Automation', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Influencer Marketing', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Keyword Research', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Campaign Management', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Facebook Marketing', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- Insert skills for Translation, Language Tutoring & Interpretation
INSERT INTO skills (skill, created_at, updated_at) VALUES
('Live Interpretation', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Subtitles', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Language Instruction', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Grammar and Vocabulary Expertise', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Pronunciation Coaching', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Active Listening', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Note-Taking', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Communication Skills', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- Insert skills for Web, Mobile & Software Dev, AI Apps & Integration
INSERT INTO skills (skill, created_at, updated_at) VALUES
('Machine Learning', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Deep Learning', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('AI Model Integration (APIs, SDKs)', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Python', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('TensorFlow', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('PyTorch', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NLP', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Computer Vision', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('RESTful APIs', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('AWS', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Azure', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('GCP', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Prompt Engineering', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Chatbot Development', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Data Preprocessing', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Model Deployment', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Performance Tuning', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- Insert skills for Web, Mobile & Software Dev, Ecommerce Development
INSERT INTO skills (skill, created_at, updated_at) VALUES
('HTML', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('CSS', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('JavaScript', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('React', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Angular', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Node.js', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('PHP', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Python', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('WooCommerce', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Magento', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('BigCommerce', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Payment Gateway Integration', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Shopping Cart Systems', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Database Management', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('API Integration', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Responsive Design', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Performance Optimization', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('SEO', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Security (SSL, Data Protection)', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- Insert skills for Web, Mobile & Software Dev, Mobile Development
INSERT INTO skills (skill, created_at, updated_at) VALUES
('Swift', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Objective-C', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Kotlin', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Java', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Flutter', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('React Native', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('UI/UX Design', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('RESTful APIs', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('SQLite', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Realm', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('JavaScript', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Android Studio', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- Insert skills for Web, Mobile & Software Dev, Other - Software Development
INSERT INTO skills (skill, created_at, updated_at) VALUES
('Object-Oriented Programming', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Software Architecture', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Full-Stack Development', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('API Development', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Version Control (Git)', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Debugging', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Unit Testing', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Agile Methodologies', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('CI/CD', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Database Design', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Cloud Integration', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('DevOps Basics', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Python', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Java', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('C#', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('C++', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- Insert skills for Web, Mobile & Software Dev, Scripts & Utilities
INSERT INTO skills (skill, created_at, updated_at) VALUES
('Python', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Bash', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('PowerShell', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('JavaScript', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Task Automation', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('File Handling', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Data Parsing', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Web Scraping', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('API Consumption', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Cron Jobs', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Regular Expressions', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('CLI Tools', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('System Monitoring', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Log Processing', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Error Handling', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Cross-Platform Compatibility', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- Insert skills for Web, Mobile & Software Dev, Web Development
INSERT INTO skills (skill, created_at, updated_at) VALUES
('HTML', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('CSS', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('JavaScript', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('React', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Angular', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vue', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Node.js', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('PHP', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Python', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Ruby', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('RESTful APIs', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('MySQL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('MongoDB', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Version Control (Git)', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Responsive Design', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Performance Optimization', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Web Security', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Cross-Browser Compatibility', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('CI/CD', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Hosting', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('DNS', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- Insert skills for Writing, Sales & Marketing Copywriting
INSERT INTO skills (skill, created_at, updated_at) VALUES
('Persuasive Writing', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Value Proposition Crafting', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('SEO Copywriting', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Audience Targeting', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Brand Voice Adaptation', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('CTA (Call-to-Action) Writing', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Email Marketing Copy', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Landing Page Copy', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Social Media Copy', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('A/B Testing', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Storytelling', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Content Strategy', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Competitor Analysis', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);


